### ISSUE TITLE
Malformed JSON in request body

### ISSUE THREAD

**Issue by jasperdanan** [ailionx/cloudflare-ddns#10]
Using functions that require `data` in request, error below occurs:

```py
>>> cf.sync_dns_from_my_ip()
{'success': False, 'errors': [{'code': 6007, 'message': 'Malformed JSON in request body'}], 'messages': [], 'result': None}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Documents\Projects\cloudflare-ddns\cloudflare_ddns\cloudflare.py", line 267, in sync_dns_from_my_ip
    self.update_record(dns_type, self.domain, ip_address, proxied=True)
  File "C:\Users\user\Documents\Projects\cloudflare-ddns\cloudflare_ddns\cloudflare.py", line 189, in update_record
    data=data
  File "C:\Users\user\Documents\Projects\cloudflare-ddns\cloudflare_ddns\cloudflare.py", line 88, in request
    raise requests.HTTPError(content['message'])
KeyError: 'message'
```

**Comment by jasperdanan** [comment]
Fix from #6 is confirmed working for this error
